## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [191]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos_mat'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos_por'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_geo'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_ing'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_his'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos_fis'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos_qui'])

In [193]:
# 1) Seu código aqui

df_mat['numero_questoes_mat'] = 24
df_mat['percentual_acertos_mat'] = df_mat['Qt_acertos_mat'] / df_mat['numero_questoes_mat']

df_por['numero_questoes_por'] = 18
df_por['percentual_acertos_por'] = df_por['Qt_acertos_por'] / df_por['numero_questoes_por']

df_geo['numero_questoes_geo'] = 8
df_geo['percentual_acertos_geo'] = df_geo['Qt_acertos_geo'] / df_geo['numero_questoes_geo']

df_ing['numero_questoes_ing'] = 8
df_ing['percentual_acertos_ing'] = df_ing['Qt_acertos_ing'] / df_ing['numero_questoes_ing']

df_his['numero_questoes_his'] = 8
df_his['percentual_acertos_his'] = df_his['Qt_acertos_his'] / df_his['numero_questoes_his']

df_fis['numero_questoes_fis'] = 12
df_fis['percentual_acertos_fis'] = df_fis['Qt_acertos_fis'] / df_fis['numero_questoes_fis']

df_qui['numero_questoes_qui'] = 12
df_qui['percentual_acertos_qui'] = df_qui['Qt_acertos_qui'] / df_qui['numero_questoes_qui']

In [194]:
df = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)
df.index += 1
df

,Qt_acertos_mat,numero_questoes_mat,percentual_acertos_mat,Qt_acertos_por,numero_questoes_por,percentual_acertos_por,Qt_acertos_geo,numero_questoes_geo,percentual_acertos_geo,Qt_acertos_ing,...,percentual_acertos_ing,Qt_acertos_his,numero_questoes_his,percentual_acertos_his,Qt_acertos_fis,numero_questoes_fis,percentual_acertos_fis,Qt_acertos_qui,numero_questoes_qui,percentual_acertos_qui
1,6,24,0.250000,7,18,0.388889,7,8,0.875,3,...,0.375,1,8,0.125,8,12,0.666667,3,12,0.250000
2,19,24,0.791667,10,18,0.555556,0,8,0.000,0,...,0.000,0,8,0.000,11,12,0.916667,8,12,0.666667
3,14,24,0.583333,16,18,0.888889,0,8,0.000,5,...,0.625,7,8,0.875,4,12,0.333333,4,12,0.333333
4,10,24,0.416667,7,18,0.388889,3,8,0.375,4,...,0.500,0,8,0.000,0,12,0.000000,8,12,0.666667
5,7,24,0.291667,2,18,0.111111,2,8,0.250,7,...,0.875,0,8,0.000,9,12,0.750000,3,12,0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,6,24,0.250000,4,18,0.222222,7,8,0.875,1,...,0.125,4,8,0.500,9,12,0.750000,3,12,0.250000
97,8,24,0.333333,1,18,0.055556,4,8,0.500,6,...,0.750,1,8,0.125,4,12,0.333333,3,12,0.250000
98,23,24,0.958333,5,18,0.277778,0,8,0.000,2,...,0.250,4,8,0.500,1,12,0.083333,5,12,0.416667
99,0,24,0.000000,10,18,0.555556,3,8,0.375,1,...,0.125,5,8,0.625,10,12,0.833333,11,12,0.916667
100,11,24,0.458333,15,18,0.833333,0,8,0.000,1,...,0.125,6,8,0.750,7,12,0.583333,2,12,0.166667

In [200]:
# 2) Seu código aqui
df['qtd_acertos_total'] = df[['Qt_acertos_mat', 'Qt_acertos_por', 'Qt_acertos_geo', 'Qt_acertos_ing', 'Qt_acertos_his', 'Qt_acertos_fis', 'Qt_acertos_qui']].sum(axis=1) 
df['qtd_acertos_total'].to_frame()

     qtd_acertos_total
1                   35
2                   48
3                   50
4                   32
5                   30
..                 ...
96                  34
97                  27
98                  40
99                  40
100                 42

[100 rows x 1 columns]

In [201]:
# 3) Seu código aqui
df['qtd_questoes_total'] = df[['numero_questoes_mat', 'numero_questoes_por', 'numero_questoes_geo', 'numero_questoes_ing', 'numero_questoes_his', 'numero_questoes_fis', 'numero_questoes_qui']].sum(axis=1)
df['percentual_geral'] = df['qtd_acertos_total'] / df['qtd_questoes_total']
df

,Qt_acertos_mat,numero_questoes_mat,percentual_acertos_mat,Qt_acertos_por,numero_questoes_por,percentual_acertos_por,Qt_acertos_geo,numero_questoes_geo,percentual_acertos_geo,Qt_acertos_ing,...,percentual_acertos_his,Qt_acertos_fis,numero_questoes_fis,percentual_acertos_fis,Qt_acertos_qui,numero_questoes_qui,percentual_acertos_qui,qtd_acertos_total,qtd_questoes_total,percentual_geral
1,6,24,0.250000,7,18,0.388889,7,8,0.875,3,...,0.125,8,12,0.666667,3,12,0.250000,35,90,0.388889
2,19,24,0.791667,10,18,0.555556,0,8,0.000,0,...,0.000,11,12,0.916667,8,12,0.666667,48,90,0.533333
3,14,24,0.583333,16,18,0.888889,0,8,0.000,5,...,0.875,4,12,0.333333,4,12,0.333333,50,90,0.555556
4,10,24,0.416667,7,18,0.388889,3,8,0.375,4,...,0.000,0,12,0.000000,8,12,0.666667,32,90,0.355556
5,7,24,0.291667,2,18,0.111111,2,8,0.250,7,...,0.000,9,12,0.750000,3,12,0.250000,30,90,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,6,24,0.250000,4,18,0.222222,7,8,0.875,1,...,0.500,9,12,0.750000,3,12,0.250000,34,90,0.377778
97,8,24,0.333333,1,18,0.055556,4,8,0.500,6,...,0.125,4,12,0.333333,3,12,0.250000,27,90,0.300000
98,23,24,0.958333,5,18,0.277778,0,8,0.000,2,...,0.500,1,12,0.083333,5,12,0.416667,40,90,0.444444
99,0,24,0.000000,10,18,0.555556,3,8,0.375,1,...,0.625,10,12,0.833333,11,12,0.916667,40,90,0.444444
100,11,24,0.458333,15,18,0.833333,0,8,0.000,1,...,0.750,7,12,0.583333,2,12,0.166667,42,90,0.466667

In [204]:
# 4) Seu código aqui
segunda_fase = df[df['qtd_acertos_total'] > 45]

print('Quantidade de alunos com nota maior que 45:')
print(segunda_fase.shape[0])

Quantidade de alunos com nota maior que 45:
31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [211]:
# seu código aqui
df_eliminados = df[(df['Qt_acertos_mat'] == 0) | 
                   (df['Qt_acertos_fis'] == 0) | 
                   (df['Qt_acertos_qui'] == 0)]

df_eliminados[['Qt_acertos_mat', 'Qt_acertos_fis', 'Qt_acertos_qui']]

    Qt_acertos_mat  Qt_acertos_fis  Qt_acertos_qui
4               10               0               8
7                6               0               4
11              10               7               0
13              20               0               3
15               7               4               0
21              23               2               0
26               0               4               8
27              11               0               0
28              21               3               0
34              14               6               0
36              11               0              11
50               8               0               8
57               7               0               8
66               1               0               6
67               5               0              10
73              11               0               9
74               1               0              11
75               9               7               0
85              15               0               4
90              23               9               0
93              14               8               0
95               0               3               8
99               0              10              11

In [214]:
# Quantos são esses alunos?
print(f'Alunos eliminados: {df_eliminados.shape[0]}.')

Alunos eliminados: 23.

In [217]:
# Qual a média desses alunos em história e geografia?

media_eliminado_his = round(df_eliminados['Qt_acertos_his'].mean(), 2)
media_eliminado_geo = round(df_eliminados['Qt_acertos_geo'].mean(), 2)

print('Média dos alunos eliminados nas questões de história: {}.'.format(media_eliminado_his))
print('Média dos alunos eliminados nas questões de geografia: {}.'.format(media_eliminado_geo))

Média dos alunos eliminados nas questões de história: 3.43.
Média dos alunos eliminados nas questões de geografia: 3.22.

In [218]:
# Monte um DataFrame com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

alunos_seguda_fase = pd.merge(left=segunda_fase, right=df_eliminados, how='inner')
alunos_seguda_fase

,Qt_acertos_mat,numero_questoes_mat,percentual_acertos_mat,Qt_acertos_por,numero_questoes_por,percentual_acertos_por,Qt_acertos_geo,numero_questoes_geo,percentual_acertos_geo,Qt_acertos_ing,...,percentual_acertos_his,Qt_acertos_fis,numero_questoes_fis,percentual_acertos_fis,Qt_acertos_qui,numero_questoes_qui,percentual_acertos_qui,qtd_acertos_total,qtd_questoes_total,percentual_geral
0,23,24,0.958333,11,18,0.611111,6,8,0.750,5,...,0.750,2,12,0.166667,0,12,0.000000,53,90,0.588889
1,21,24,0.875000,13,18,0.722222,1,8,0.125,5,...,0.875,3,12,0.250000,0,12,0.000000,50,90,0.555556
2,11,24,0.458333,14,18,0.777778,6,8,0.750,3,...,0.375,0,12,0.000000,11,12,0.916667,48,90,0.533333
3,11,24,0.458333,16,18,0.888889,3,8,0.375,4,...,0.875,0,12,0.000000,9,12,0.750000,50,90,0.555556
4,23,24,0.958333,11,18,0.611111,7,8,0.875,7,...,0.750,9,12,0.750000,0,12,0.000000,63,90,0.700000

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [236]:
arquivo = 'registros de vacinacao covid ACRE.csv'

In [239]:
# 1) Sua solução aqui
df = pd.read_csv(arquivo, sep=';')

In [241]:
df.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

In [252]:
# Quantas vacinas estão registradas nessa base?

print('Total de vacinas registrada em nossa BD:')
print(df.shape[0])

Total de vacinas registrada em nossa BD:
169071

In [253]:
# 2) Quantos pacientes foram vacinados? (considere um paciente para cada valor único de paciente_id)
print('Total de pacientes vacinados:')
print(df['paciente_id'].nunique())

Total de pacientes vacinados:
120517

In [270]:
# 3) Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método .unique().
primeira_dose = df['vacina_descricao_dose'].unique()[0]
pacientes_prim_dose = df[df['vacina_descricao_dose'] == primeira_dose]
total_pac_primeira_dose = pacientes_prim_dose['paciente_id'].nunique()

print('Total de pacientes que já tomaram a primeira dose:')
print(total_pac_primeira_dose)

Total de pacientes que já tomaram a primeira dose:
119713

In [274]:
# 4) Quantos pacientes com menos de 18 anos foram vacinados?
df_menor = df[df["paciente_idade"]<18]
total_menor_18 = df_menor['paciente_id'].nunique()

print('Pacientes com menos de 18 anos que foram vacinados:')
print(total_menor_18)

Pacientes com menos de 18 anos que foram vacinados:
47

In [293]:
# 5) Quantos estabelecimentos aplicaram vacina no Acre?

qtd_estab_aplicaram_vacina = df['estabelecimento_razaosocial'].nunique()
print('Total de estabelecimento que aplicaram vacina no ACRE:')
print(qtd_estab_aplicaram_vacina)

print("\n\033[1;31;47mDados dos estabelecimentos:\033[m")

df.loc[:,'estabelecimento_valor' : 'estabelecimento_uf']

Total de estabelecimento que aplicaram vacina no ACRE:
42

Dados dos estabelecimentos:

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,3541592,PREFEITURA MUNICIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE MARIA DAS DORES DE PAULA,120050,SENA MADUREIRA,AC
1,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
2,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
3,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
4,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
...,...,...,...,...,...,...
169066,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
169067,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
169068,2001039,PREFEITURA MUNICIPAL DE CAPIXABA,UNIDADE DE SAUDE DA FAMILIA DR LUIZ FERNANDO M...,120017,CAPIXABA,AC
169069,2002876,SECRETARIA MUNCIPAL DE SAUDE,CENTRO DE SAUDE RAIMUNDA PORFIRIO DE BRITO RAMOS,120013,BUJARI,AC
169070,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [295]:
# 1) crie uma cópia do DataFrame original, contendo somente os registros de vacinas realizadas a menores de 18 anos
df_menor_18 = df[df["paciente_idade"]<18].copy()
df_menor_18.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55 entries, 1567 to 164449
Data columns (total 34 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   document_id                               55 non-null     object
 1   paciente_id                               55 non-null     object
 2   paciente_idade                            55 non-null     int64
 3   paciente_datanascimento                   55 non-null     object
 4   paciente_enumsexobiologico                55 non-null     object
 5   paciente_racacor_codigo                   55 non-null     int64
 6   paciente_racacor_valor                    55 non-null     object
 7   paciente_endereco_coibgemunicipio         52 non-null     float64
 8   paciente_endereco_copais                  52 non-null     float64
 9   paciente_endereco_nmmunicipio             52 non-null     object
 10  paciente_endereco_nmpais                  52 non-null     object
 11  paciente_endereco_uf                      52 non-null     object
 12  paciente_endereco_cep                     42 non-null     float64
 13  paciente_nacionalidade_enumnacionalidade  55 non-null     object
 14  estabelecimento_valor                     55 non-null     int64
 15  estabelecimento_razaosocial               55 non-null     object
 16  estalecimento_nofantasia                  55 non-null     object
 17  estabelecimento_municipio_codigo          55 non-null     int64
 18  estabelecimento_municipio_nome            55 non-null     object
 19  estabelecimento_uf                        55 non-null     object
 20  vacina_grupoatendimento_codigo            55 non-null     int64
 21  vacina_grupoatendimento_nome              54 non-null     object
 22  vacina_categoria_codigo                   54 non-null     float64
 23  vacina_categoria_nome                     54 non-null     object
 24  vacina_lote                               55 non-null     object
 25  vacina_fabricante_nome                    55 non-null     object
 26  vacina_fabricante_referencia              53 non-null     object
 27  vacina_dataaplicacao                      55 non-null     object
 28  vacina_descricao_dose                     55 non-null     object
 29  vacina_codigo                             55 non-null     int64
 30  vacina_nome                               55 non-null     object
 31  sistema_origem                            55 non-null     object
 32  data_importacao_rnds                      55 non-null     object
 33  id_sistema_origem                         0 non-null      float64
dtypes: float64(5), int64(6), object(23)
memory usage: 15.0+ KB

In [296]:
# 2) crie uma lista das colunas desse DataFrame com o atributo de DataFrame .columns()
df_menor.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [305]:
# 3) Nesse DataFrame faça uma contagem do campo vacina_categoria_nome.

print('Total de vacinas')


df_menor['vacina_categoria_nome'].value_counts()

Total de vacinas

Povos Indígenas                     33
Trabalhadores de Saúde               9
Povos e Comunidades Tradicionais     9
Comorbidades                         2
Faixa Etária                         1
Name: vacina_categoria_nome, dtype: int64

In [319]:
# 4) a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.

lista_variaveis = ['estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']
df_menor_lista = df_menor.loc[:,lista_variaveis]

print('Lista com os nomes dos estabelecimentos:')
lista_variaveis

Lista com os nomes dos estabelecimentos:

['estabelecimento_valor',
 'estabelecimento_razaosocial',
 'estalecimento_nofantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [322]:
# 5) usando o método .loc, selecione somente essas variáveis
df_menor_lista = df_menor_lista.drop_duplicates()
df_menor_lista.shape

df_menor_lista.loc[:,lista_variaveis]

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC

In [323]:
# 6) Aplique o método .drop_duplicates e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

df_menor_lista = df_menor_lista['estabelecimento_razaosocial'].drop_duplicates()
df_menor_lista.reset_index(drop=True, inplace=True)
df_menor_lista.index += 1
df_menor_lista.to_frame()

                          estabelecimento_razaosocial
1              PREFEITURA MUNICIPAL DE EPITACIOLANDIA
2                  PREFEITURA MUNICIPAL DE RIO BRANCO
3             PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL
4                       PREFEITURA MUNICIPAL DE FEIJO
5   DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...
6                PREFEITURA MUNICIPAL DE PORTO WALTER
7                PREFEITURA MUNICIPAL DE ASSIS BRASIL
8                    PREFEITURA MUNICIPAL DE TARAUACA
9   DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...
10    DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA
11              SECRETARIA DE ESTADO DE SAUDE DO ACRE
12                                MINISTERIO DA SAUDE
13                 PREFEITURA MUNICIPAL DE PORTO ACRE
14                     PREFEITURA MUNICIPAL DE JORDAO